name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main  # or the branch you want to trigger deployment from (e.g., 'master')

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show secret (for debugging purposes only, do not leave in production)
        run: echo ${{ secrets.AZURE_SPEECH_FUNCTION_KEY }}
        env:
          AZURE_SPEECH_FUNCTION_KEY: ${{ secrets.AZURE_SPEECH_FUNCTION_KEY }}

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        env:
          REACT_APP_AZURE_SPEECH_FUNCTION_KEY: ${{ secrets.AZURE_SPEECH_FUNCTION_KEY }}
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          #force_orphan: true
